### ISSUE TITLE
Keep the Wikipedia index up-to-date

### ISSUE THREAD

**Issue by hubgit** [elastic/elasticsearch-river-wikipedia#10]
Once the initial dump has been processed, could the river listen for Wikipedia updates (broadcast on irc://irc.wikimedia.org/en.wikipedia) and keep the index up-to-date?

**Comment by dadoonet** [comment]
Thanks for opening this!

But we won't support new features as rivers are now [deprecated](https://www.elastic.co/blog/deprecating_rivers).
