### ISSUE TITLE
River only imports ~500k wikipedia documents into index.

### ISSUE THREAD

**Issue by ryanrozich** [elastic/elasticsearch-river-wikipedia#49]
This weekend I tried importing wikipedia into an ES index using the river. Only about 500K documents were imported. Because I am running on a managed ES cluster (QBox) I couldn't check the server logs to see why the import stopped.

But, since the readme.md indicates that rivers were deprecated and to look at stream2es instead, I decided to try that. When importing wikipedia using stream2es it also stopped at about 500k documents. This time I was able to see the logs and opened an issue with the stream2es project

[stream2es indexing of wikipedia fails at about 540K docs with IOException: unexpected end of stream](https://github.com/elastic/stream2es/issues/47)
(see this issue for the stack trace)

The comment on that issue indicates that it might be a problem with the [WikiXMLSAXParser](https://github.com/elastic/elasticsearch-river-wikipedia/blob/master/src/main/java/org/elasticsearch/river/wikipedia/support/WikiXMLSAXParser.java) class which stream2es depends on and is maintained in this project. This would explain why both using the river and stream2es failed at about the same place in the import process. Perhaps the wikipedia dump file format changed in a way that broke this parser?

At the end of the day I would love to get wikipedia imported for a project I am working on whether or not I use the river or stream2es. Has anyone gotten wikipedia to import recently? Any tips on how to get this to work?

**Comment by dadoonet** [comment]
Might be better to download first locally the Wikipedia dump instead of streaming it ?

I guess it could be caused by a Network issue?

**Comment by ryanrozich** [comment]
Does the river plugin support downloading a local copy? Is there a parameter that I need to set when I start the river?

**Comment by dadoonet** [comment]
This should work:

    {
        "type" : "wikipedia",
        "wikipedia" : {
            "url" : "file:/path/to/dump"
        }
    }

**Comment by ryanrozich** [comment]
Thanks, since I am using a managed ES cluster (QBox) I dont have access to the filesystem of the node so I couldn't try this for the river. But was able to try using stream2es since that is running on another machine that I manage. Since it looks like the two projects share the core bz2 streaming code and SAX parser I thought I'd add the results to this issue as well

Per the recommendation from @dadoonet, I downloaded the dump locally and ran stream2es using the local dump file. This time it did not fail at ~500k documents. It is still running and chugging along at about 13.5MM documents so far so I assume this should finish. @drewr mentioned I should expect 15MM or so documents when it is done indexing

So, it would appear that streaming the dump file from the server causes the issue. It is a nice feature to be able to process the file directly over the network stream rather than having to have the extra step (and disk space) of downloading an 11GB+ dump file first, but at least this gives me a workaround to keep developing.

Thanks for the help!

**Comment by dadoonet** [comment]
This project has been stopped since elasticsearch 2.0.
